title: Volodymyr
email: Shchuryshyn@protonmail.com
description: >-
  Electrical Engineering Student | Tech Enthusiast
baseurl: "" 
url: "https://vstimeless.github.io"
github_username: vstimeless
twitter_username: vstimeless
linkedin_username: vstimeless

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Collections
collections:
  projects:
    output: true
    permalink: /projects/:title/

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/
  - .gitignore
